version: '3.3'

services:
  trainingdev:
    image: jenslaufer/docker-generic-tensorflow-python:tf_1_13_1-py3-cpu
    container_name: rltrader-dev
    environment:
      - MONGODB_URI=mongodb://rltrainingdb-dev
    volumes: 
      - $DATA_DIR:/rldata
      - ./:/code
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    depends_on: 
      - rltrainingdbdev

  data-analysis-dashboard:
    image: jenslaufer/rl-data-analysis:0.1.1
    container_name: data-analysis-dashboard-dev
    ports:
      - '8081:3838'
    environment:
      - "MONGODB_URI=mongodb://rltrainingdb-dev"
    depends_on: 
      - rltrainingdbdev

  rltrainingdbdev:
    image: mongo:3.6.13
    container_name: "rltrainingdb-dev"
    ports:
      - 37017:27017
    volumes:
      - $DB_DIR:/data/db
    command: mongod
