version: '3.3'

services:
  trainingdev:
    image: jenslaufer/docker-generic-tensorflow-python:tf_1_13_1-py3-cpu
    container_name: rltrader-dev
    volumes: 
      - $DATA_DIR:/rldata
      - ./:/code
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    depends_on: 
      - rltrainingdbdev
  rltrainingdbdev:
    image: mongo:3.6.13
    container_name: "rltrainingdb-dev"
    ports:
      - 27017:27017
    volumes:
      - $DB_DIR:/data/db
    command: mongod