version: '3.3'

services:
  training:
    image: jenslaufer/docker-generic-tensorflow-python:tf_1_13_1-py3-cpu
    container_name: rltrader
    volumes: 
      - ./data:/data
      - ./src:/src
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    secrets:
      - my_secret
      
secrets:
  my_secret:
    file: ./.ssh/rl