version: '3.3'

services:
  training:
    image: jenslaufer/docker-generic-tensorflow-python:tf_1_13_1-py3-cpu
    container_name: rltrader
    environment:
      - MODULE_REPO=git+https://github.com/jenslaufer/rl-trader.git@feature/training_metric
      - MODULE_CMD=rltrader.trainer
    volumes: 
      - $DATA_DIR:/rldata
    depends_on: 
      - rltrainingdb

  rltrainingdb:
    image: mongo:3.6.13
    container_name: "rltrainingdb"
    ports:
      - 27017:27017
    command: mongod