version: '3.0'

services:
  training:
    image: jenslaufer/docker-generic-tensorflow-python:tf_1_13_1-py3-cpu
    container_name: rltrader
    environment:
      - MODULE_REPO=git+git@bitbucket.org:jenslaufer/rl-trader.git
      - MODULE_CMD=trading.train