version: '3.1'

services:
  training:
    image: jenslaufer/docker-generic-tensorflow-python:tf_1_13_1-py3-cpu
    container_name: rltrader
    environment:
      - MODULE_REPO=git+ssh://git@bitbucket.org:jenslaufer/rl-trader.git
      - MODULE_CMD=trading.train

secrets:
  my_secret:
    file: ./.ssh/rl