---
title: "Analysis Reinforcement Results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F)
```
```{r}
library(tidyverse)
library(glue)
```



```{r}
INDEX = ""
LOGS_DIR = '../src'
DATA_DIR = '../src/data'
```


```{r}
load <- function(filename) {
  return(
    read_csv(filename) %>%
      mutate(action=as.factor(action)) %>%
      mutate(net_worth = balance + asset_balance * price) %>%
      mutate(step = X1) %>%
      select(-X1, -done) %>%
      filter(price > 0)
  )
}
```






```{r}
vis.df = function(df) {
  df %>%
    gather(-step, -action, key = "feature", value = "value") %>%
    ggplot(aes(x = step, y = value)) +
    geom_line() +
    facet_wrap( ~ feature, scales = 'free')
}
```

```{r}
df <- read_csv(glue('{DATA_DIR}/btc.csv'))
```


```{r}
train.df <- load(glue('{LOGS_DIR}/train{INDEX}.csv'))
```

```{r fig.height=10, fig.width=20}
vis.df(train.df)
```



```{r}
test.df <- load(glue('{LOGS_DIR}/test{INDEX}.csv'))
```


```{r fig.height=15, fig.width=20}
test.df %>% vis.df()
```





```{r}
test.df %>%
  group_by(action) %>%
  summarise(n=n())
```


```{r}
profits <- test.df %>% 
  mutate(diff = (balance - lag(balance))) %>% filter(diff > 0 | diff < 0) %>% select(step, diff)
```

```{r}
profits
```

```{r}
test.df %>% tail(10)
```


```{r}
test.df %>% dim()
```

